name: "privileged-requester"
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions:
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
    - uses: ./
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
        robotUserToken: ${{ secrets.REPO_GITHUB_TOKEN }}
        path: config/privileged-requester.yaml
        prCreator: ${{ github.event.pull_request.user.login }}
        prNumber: ${{ github.event.pull_request.number }}
        checkCommits: "true"
        checkDiff: "true"
        checkLabels: "true"
