name: "units-test"
on:
  pull_request:

jobs:
    # unit tests
    units:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - run: npm ci
      - run: npm test
