name: "units-test"
on:
  pull_request:

jobs:
    # unit tests
    units:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - run: npm ci
      - run: npm test
