name: "units-test"
on:
  pull_request:

jobs:
    # unit tests
    units:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - run: npm ci
      - run: npm test
