name: "units-test"
on:
  pull_request:

jobs:
    # unit tests
    units:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - run: npm ci
      - run: npm test
