name: "units-test"
on:
  pull_request:

jobs:
#  # unit tests
#  units:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - run: npm ci
#    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
        path: config/privileged-requester.yaml
        prCreator: ${{ github.event.pull_request.user.login }}
        prNumber: ${{ github.event.pull_request.number }}
